# ----------------------- #
#      Main Configs       #
# ----------------------- #
url: http://blog.ashwani.co.in
disqusimage: http://blog.ashwani.co.in/images/heroBack.jpg
name: Ashwani's Tech World - Giving back to community
title: Ashwani's Tech World - Giving back to community
subtitle: Sharing Knowledge - Best way to keep your brain juicy.
author: Ashwani Kumar
blog_search: TRUE
simple_searchxxx: http://google.com/search
description: This is my personal blog I use for expressing my views, to document the issues I encountered and to help give something back to the world.
keywords: TheAshwaniK, Ashwani Kumar Blog, Blog , Functional Blog, Technical Blog, Telecom Blog, KIS , Kabira, Kabira provisioning , KPSA, Development, provisioning
#prof_website: www.ashwani.co.in
stackoverflow: https://stackoverflow.com/users/1915916/theashwanik?tab=badges
stackoverflow_name: theashwanik

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

#date_format: "%Y-%m-%d"  # e.g. 2014-07-03
#time_format: "%H:%M"     # 24 hour time

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: aryan.ashwani@gmail.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year-:month-:day/:title/
source: source
destination: public
plugins_dir: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
   
    #- smart
highlighter: pygments # default python pygments have been replaced by pygments.rb
#paginate: 3          # Posts per page on the blog index
#pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
#paginate_path: "blog/page/:num"  # Directory base for pagination URLs eg. /posts/2/

pagination:
  limit: 10
  per_page: 3
  title_suffix: " (page :num)"
  permalink: "blog/page/:num"
  reversed: false # Reverse the order of the documents

recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"
#excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [custom/asides/gravatar.html, custom/asides/subscribe.html, asides/recent_posts.html, custom/asides/category_cloud.html, custom/asides/tags.html, asides/twitter.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: TheAshwaniK
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true
github_feedback: true
gittip: true


# LinkedIn repositories
linkedin_user: ashwaniaryan

#Coderwall endorse button
coderwall_user:  TheAshwaniK
coderwall_button: false


# LinkedIn repositories
linkedin_user: ashwaniaryan

# Twitter
#twitter_user: TheAshwaniK
twitter_user: 
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

#Coderwall endorse button
coderwall_user:  TheAshwaniK
coderwall_button: false

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
# googleplus_user: 114156830425943630021
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: theashwanik
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-37485375-1

# Facebook Like
facebook_like: true

# Gravatar
gravatar_email: aryan.ashwani@gmail.com

# OneMonthRailsReferrals
OneMonthRailsReferrals: true

# Tag Generator from https://github.com/robbyedwards/octopress-tag-pages
# I dint want to change default settings
#
#tag_dir: The subfolder to build tag pages in (default is tags).
#tag_title_prefix: The string used before the tag name in the page title (default is Tag:).
tag_dir: tags
tag_title_prefix: 'Tag:'

plugins:
  - jekyll-sitemap
  - octopress-paginate
  - octopress-debugger


# Posts in the sidebar Popular Posts section
#popular_posts_count: 5

#https://www.narga.net/improve-octopress-advanced-tweaks-tips/
#http://techtinkering.com/2011/08/17/improving-related-posts-on-jekyll/
#lsi: true

